package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Lugares generated by hbm2java
 */
@Entity
@Table(name="Lugares"
    , uniqueConstraints = @UniqueConstraint(columnNames={"ciudad", "barrio", "Pais_pais"}) 
)
public class Lugar  implements java.io.Serializable {

     private Integer idLugar;
     private Pais paises;
     private String ciudad;
     private String barrio;

    public Lugar() {
    }
	
    public Lugar(Pais paises, String ciudad, String barrio) {
        this.paises = paises;
        this.ciudad = ciudad;
        this.barrio = barrio;
    }
    
    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="idLugar", unique=true, nullable=false)
    public Integer getIdLugar() {
        return this.idLugar;
    }
    
    public void setIdLugar(Integer idLugar) {
        this.idLugar = idLugar;
    }

    @ManyToOne(fetch=FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name="Pais_pais", nullable=false)
    public Pais getPaises() {
        return this.paises;
    }
    
    public void setPaises(Pais paises) {
        this.paises = paises;
    }

    
    @Column(name="ciudad", nullable=false, length=45)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    
    @Column(name="barrio", nullable=false, length=45)
    public String getBarrio() {
        return this.barrio;
    }
    
    public void setBarrio(String barrio) {
        this.barrio = barrio;
    }
}


