package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Proveedores generated by hbm2java
 */
@Entity
@Table(name="Proveedores")
public class Proveedor  implements java.io.Serializable {

    private int idProveedores;
    private Lugar lugares;
    private String razonSocial;
    private String direccion;
    private String contactoTelefonico;
    private String sitioWeb;
    private String email;
    private Set<Producto> productos = new HashSet<>(0);

    public Proveedor() {
    }
	
    public Proveedor(int idProveedores, Lugar lugares, String razonSocial, String direccion, String contactoTelefonico, String sitioWeb, String email) {
        this.idProveedores = idProveedores;
        this.lugares = lugares;
        this.razonSocial = razonSocial;
        this.direccion = direccion;
        this.contactoTelefonico = contactoTelefonico;
        this.sitioWeb = sitioWeb;
        this.email = email;
    }
    public Proveedor(int idProveedores, Lugar lugares, String razonSocial, String direccion, String contactoTelefonico, String sitioWeb, String email, Set<Producto> productoses) {
       this.idProveedores = idProveedores;
       this.lugares = lugares;
       this.razonSocial = razonSocial;
       this.direccion = direccion;
       this.contactoTelefonico = contactoTelefonico;
       this.sitioWeb = sitioWeb;
       this.email = email;
       this.productos = productoses;
    }
   
     @Id 

    
    @Column(name="idProveedores", unique=true, nullable=false)
    public int getIdProveedores() {
        return this.idProveedores;
    }
    
    public void setIdProveedores(int idProveedores) {
        this.idProveedores = idProveedores;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Lugar_idLugar", nullable=false)
    public Lugar getLugares() {
        return this.lugares;
    }
    
    public void setLugares(Lugar lugares) {
        this.lugares = lugares;
    }

    
    @Column(name="razonSocial", nullable=false, length=45)
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    
    @Column(name="direccion", nullable=false, length=45)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="contactoTelefonico", nullable=false, length=45)
    public String getContactoTelefonico() {
        return this.contactoTelefonico;
    }
    
    public void setContactoTelefonico(String contactoTelefonico) {
        this.contactoTelefonico = contactoTelefonico;
    }

    
    @Column(name="sitioWeb", nullable=false, length=45)
    public String getSitioWeb() {
        return this.sitioWeb;
    }
    
    public void setSitioWeb(String sitioWeb) {
        this.sitioWeb = sitioWeb;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedores")
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
}


