package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bancos generated by hbm2java
 */
@Entity
@Table(name="Bancos")
public class Banco  implements java.io.Serializable {

     private int idBancos;  
     private String nombre;
     private Set<Factura> facturas = new HashSet<>(0);

    public Banco() {
    }
	
    public Banco(int idBancos, String nombre) {
        this.idBancos = idBancos;
        this.nombre = nombre;
    }
    public Banco(int idBancos, String nombre, Set<Factura> facturases) {
       this.idBancos = idBancos;
       this.nombre = nombre;
       this.facturas = facturases;
    }
   
    @Id
    @Column(name="idBancos", unique=true, nullable=false)
    public int getIdBancos() {
        return this.idBancos;
    }
    
    public void setIdBancos(int idBancos) {
        this.idBancos = idBancos;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @OneToMany(fetch=FetchType.LAZY)
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }
}


