package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Descuentos generated by hbm2java
 */
@Entity
@Table(name="Descuentos")
public class Descuento  implements java.io.Serializable {

     private Integer idPromociones;
     private int porcentaje;
     private Date fechaInicio;
     private Date fechaFinal;
     private String descripcion;

    public Descuento() {
    }
	
    public Descuento(int porcentaje, Date fechaInicio, Date fechaFinal, String descripcion) {
        this.porcentaje = porcentaje;
        this.fechaInicio = fechaInicio;
        this.fechaFinal = fechaFinal;
        this.descripcion = descripcion;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idPromociones", unique=true, nullable=false)
    public Integer getIdPromociones() {
        return this.idPromociones;
    }
    
    public void setIdPromociones(Integer idPromociones) {
        this.idPromociones = idPromociones;
    }

    
    @Column(name="porcentaje", nullable=false)
    public int getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(int porcentaje) {
        this.porcentaje = porcentaje;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFinal", nullable=false, length=10)
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }

    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
}


