package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetalleCompraId generated by hbm2java
 */
@Embeddable
public class DetalleCompraId  implements java.io.Serializable {


     private int pedidosIdPedidos;
     private int productosIdProductos;

    public DetalleCompraId() {
    }

    public DetalleCompraId(int pedidosIdPedidos, int productosIdProductos) {
       this.pedidosIdPedidos = pedidosIdPedidos;
       this.productosIdProductos = productosIdProductos;
    }
   


    @Column(name="Pedidos_idPedidos", nullable=false)
    public int getPedidosIdPedidos() {
        return this.pedidosIdPedidos;
    }
    
    public void setPedidosIdPedidos(int pedidosIdPedidos) {
        this.pedidosIdPedidos = pedidosIdPedidos;
    }


    @Column(name="Productos_idProductos", nullable=false)
    public int getProductosIdProductos() {
        return this.productosIdProductos;
    }
    
    public void setProductosIdProductos(int productosIdProductos) {
        this.productosIdProductos = productosIdProductos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DetalleCompraId) ) return false;
		 DetalleCompraId castOther = ( DetalleCompraId ) other; 
         
		 return (this.getPedidosIdPedidos()==castOther.getPedidosIdPedidos())
 && (this.getProductosIdProductos()==castOther.getProductosIdProductos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPedidosIdPedidos();
         result = 37 * result + this.getProductosIdProductos();
         return result;
   }   


}


