package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleCompra generated by hbm2java
 */
@Entity
@Table(name="DetalleCompra")
public class DetalleCompra  implements java.io.Serializable {


     private DetalleCompraId id;
     private Producto productos;
     private int cantidad;
     private long precioUnitario;

    public DetalleCompra() {
    }

    public DetalleCompra(DetalleCompraId id, Producto productos, int cantidad, long precioUnitario) {
       this.id = id;
       this.productos = productos;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="pedidosIdPedidos", column=@Column(name="Pedidos_idPedidos", nullable=false) ), 
        @AttributeOverride(name="productosIdProductos", column=@Column(name="Productos_idProductos", nullable=false) ) } )
    public DetalleCompraId getId() {
        return this.id;
    }
    
    public void setId(DetalleCompraId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Productos_idProductos", nullable=false, insertable=false, updatable=false)
    public Producto getProductos() {
        return this.productos;
    }
    
    public void setProductos(Producto productos) {
        this.productos = productos;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="precioUnitario", nullable=false)
    public long getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(long precioUnitario) {
        this.precioUnitario = precioUnitario;
    }




}


