package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Envios generated by hbm2java
 */
@Entity
@Table(name="Envios")
public class Envio  implements java.io.Serializable {


    private int idEnvio = 0;
    private Date fechaSalida;
    private Set<EstadoEnvio> estadoEnvios = new HashSet<>(0);
    private Set<Pedido> pedidos = new HashSet<>(0);
     

    public Envio() {
    }
	
    public Envio(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }
    public Envio(Date fechaSalida, Set estadoEnvioses, Set pedidoses) {
       this.estadoEnvios = estadoEnvioses;
       this.fechaSalida = fechaSalida;
       this.pedidos = pedidoses;
    }
     
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idEnvio", unique=true, nullable=false)
    public int getIdEnvio() {
        return this.idEnvio;
    }
    
    public void setIdEnvio(int idEnvio) {
        this.idEnvio = idEnvio;
    }

    @Column(name="fechaSalida", unique=true, nullable=false)
    public Date getFechaSalida() {
        return fechaSalida;
    }

    public void setFechaSalida(Date fechaSalida) {
        this.fechaSalida = fechaSalida;
    }

    @OneToMany(fetch=FetchType.LAZY)
    public Set<EstadoEnvio> getEstadoEnvios() {
        return this.estadoEnvios;
    }
    
    public void setEstadoEnvios(Set<EstadoEnvio> estadoEnvioses) {
        this.estadoEnvios = estadoEnvioses;
    }

    @OneToMany(fetch=FetchType.EAGER, targetEntity = Pedido.class)
    @JoinColumn(name="Envios_idEnvio")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidoses) {
        this.pedidos = pedidoses;
    }
    
    @Override
    public String toString(){
        String s = "Estado envio: " + " " + this.getEstadoEnvios().toString() + "Pedidos: " + this.getPedidos().toString();
        return s;
    }
}


