package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="Pedidos")
public class Pedido  implements java.io.Serializable {

     private int idPedidos = 0;
     private String direccionEnvio;
     private Date fechaLlegada;
     private long valorTotal;
     
     @Cascade(CascadeType.ALL)
     private Set<DetalleCompra> detalleCompras = new HashSet<>(0);

    public Pedido() {
    }
	
    public Pedido(String direccionEnvio, Date fechaLlegada, long valorTotal) {
        this.direccionEnvio = direccionEnvio;
        this.valorTotal = valorTotal;
        this.fechaLlegada = fechaLlegada;
    }
    
    public Pedido(String direccionEnvio, Date fechaLlegada, long valorTotal, Set detalleCompras) {
       this.direccionEnvio = direccionEnvio;
       this.valorTotal = valorTotal;
       this.fechaLlegada = fechaLlegada;
       this.detalleCompras = detalleCompras;
    }
   
    @Id 
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="idPedidos", unique=true, nullable=false)
    public int getIdPedidos() {
        return this.idPedidos;
    }
    
    public void setIdPedidos(int idPedidos) {
        this.idPedidos = idPedidos;
    }

    @Column(name="direccionEnvio", nullable=false, length=45)
    public String getDireccionEnvio() {
        return this.direccionEnvio;
    }
    
    public void setDireccionEnvio(String direccionEnvio) {
        this.direccionEnvio = direccionEnvio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaLlegada", nullable=false, length=10)
    public Date getFechaLlegada() {
        return this.fechaLlegada;
    }
    
    public void setFechaLlegada(Date fechaLlegada) {
        this.fechaLlegada = fechaLlegada;
    }
    
    @Column(name="valorTotal", nullable=false)
    public long getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(long valorTotal) {
        this.valorTotal = valorTotal;
    }
    
    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name = "Pedidos_idPedidos")
    public Set<DetalleCompra> getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set<DetalleCompra> detalleCompras) {
        this.detalleCompras = detalleCompras;
    }
}