package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name="Productos")
public class Producto  implements java.io.Serializable {

     private int idProductos;
     private Categoria categoria;
     private Descuento descuentos;
     private String descripcion;
     private long precioLista;
     private Proveedor proveedor;
     private Set<MetaDato> metaDatos = new HashSet<>(0);

    public Producto() {
    }
	
    public Producto(int idProductos, Categoria categoria, Descuento descuentos, String descripcion, Proveedor proveedor, long precioLista) {
        this.idProductos = idProductos;
        this.descuentos = descuentos;
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.descripcion = descripcion;
        this.precioLista = precioLista;
    }
    
    public Producto(int idProductos, Categoria categoria, Descuento descuentos, String descripcion, Proveedor proveedor, long precioLista, Set<MetaDato> metaDatoses) {
        this.idProductos = idProductos;
        this.descuentos = descuentos;
        this.descripcion = descripcion;
        this.categoria = categoria;
        this.proveedor = proveedor;
        this.precioLista = precioLista;
        this.metaDatos = metaDatoses;
    }
   
    @Id
    @Column(name="idProductos", unique=true, nullable=false)
    public int getIdProductos() {
        return this.idProductos;
    }
    
    public void setIdProductos(int idProductos) {
        this.idProductos = idProductos;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Descuentos_idPromociones", nullable=false)
    public Descuento getDescuentos() {
        return this.descuentos;
    }
    
    public void setDescuentos(Descuento descuentos) {
        this.descuentos = descuentos;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Categorias_idCategorias", nullable=false)
    public Categoria getCategoria() {
        return categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
        
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="precioLista", nullable=false)
    public long getPrecioLista() {
        return this.precioLista;
    }
    
    public void setPrecioLista(long precioLista) {
        this.precioLista = precioLista;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Productos_has_MetaDatos", catalog="coswg3", joinColumns = { 
        @JoinColumn(name="Productos_idProductos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="MetaDatos_idMetaDatos", nullable=false, updatable=false) })
    public Set<MetaDato> getMetaDatos() {
        return this.metaDatos;
    }
    
    public void setMetaDatos(Set<MetaDato> metaDatoses) {
        this.metaDatos = metaDatoses;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Proveedores_idProveedores", nullable=false)
    public Proveedor getProveedores() {
        return this.proveedor;
    }
    
    public void setProveedores(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
}


