package com.cosw.superstuff.persistencia;
// Generated Feb 18, 2015 10:14:56 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tenderos generated by hbm2java
 */
@Entity
@Table(name="Tenderos")
public class Tendero  implements java.io.Serializable {

    public static final String CINCOREP = "5";
    public static final String CUATROREP = "4";
    public static final String TRESREP = "3";
    public static final String DOSREP = "2";
    public static final String UNAREP = "1";
    
    private int idTenderos;
    private String nombre;
    private String reputacion;
    private String usuario;
    private String contrasena;
    private Set<Tienda> tiendas = new HashSet<>(0);

    public Tendero() {
    }
	
    public Tendero(int idTenderos, String nombre, String usuario, String contrasena) {
        this.idTenderos = idTenderos;
        this.nombre = nombre;
        this.reputacion = TRESREP;
    }
    
    public Tendero(int idTenderos, String nombre, String usuario, String contrasena, Set<Tienda> tiendases) {
       this.idTenderos = idTenderos;
       this.nombre = nombre;
       this.reputacion = TRESREP;
       this.tiendas = tiendases;
    }
   
    @Id
    @Column(name="idTenderos", unique=true, nullable=false)
    public int getIdTenderos() {
        return this.idTenderos;
    }
    
    public void setIdTenderos(int idTenderos) {
        this.idTenderos = idTenderos;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="reputacion", nullable=false, length=2)
    public String getReputacion() {
        return this.reputacion;
    }
    
    public void setReputacion(String reputacion) {
        this.reputacion = reputacion;
    }
    
    @Column(name="usuario")
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    
    @Column(name="contrasena")
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    @OneToMany(fetch=FetchType.LAZY)
    @JoinColumn(name = "Tenderos_idTenderos")
    public Set<Tienda> getTiendas() {
        return this.tiendas;
    }
    
    public void setTiendas(Set<Tienda> tiendas) {
        this.tiendas = tiendas;
    }
}


